apiVersion: v1
kind: Service
metadata:
  name: alertmanager-example-service
  namespace: prometheus-operator
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: alertmanager-main
