global:
  resolve_timeout: 5m
  slack_api_url: <your api url>

# The root route. This route is used as the default
# if there are no matches in the child routes.
route:
  group_by: [ alerttype ]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'default_receiver'
  # A child route - all critical alerts follow this route
  # and use the receiver 'pager_receiver'
  routes:
  - match:
      category: monitor_receiver
    receiver: monitor_channel
    group_wait: 1m

receivers:
- name: 'default_receiver'
  slack_configs:
  - channel: 'prometheus-alertmanager-test'
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "*Description*: {{ .CommonAnnotations.description }}\n*Severity*: {{ .CommonLabels.severity }}"
- name: pager-receiver
  pagerduty_configs:
  - service_key: <your service key>

inhibit_rules:
    # An alert needs to match this label to inhibit another alert
  - source_match:
      severity: 'critical'
    # The alert that gets muted 
    target_match:
      severity: 'warning'
    # Both source and target need to have the same value to inhibit the alert
    equal: [ alerttype ]
